config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  get 'especial', to: 'welcome#index' #Podemos crear rutas personalizadas apuntando a un controlador y accion especificandolas despues del to:
  get 'welcome/ejemplos'

  resources :articulos do
    resources :comentarios, only: [:create, :destroy, :update]
  end
=begin
    get '/articulos'  index
    post '/articulos'  create
    delete '/articulos/:id'  destroy
    get '/articulos/:id'  show
    get '/articulos/new'  new
    get '/articulos/:id/edit'  edit
    patch '/articulos/:id'  update
    put '/articulos/:id'  update
=end

  root 'welcome#index'

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
	belongs_to :usuario
	has_many :comentarios
	validates :titulo, presence: true, uniqueness: true #Valida que el elemento no venga vacio y que no se repita
	validates :cuerpo, presence: true, length: { minimum: 20 } #Valida que el campo cuerpo no esté vacio y que contenga un minimo de 20 caracteres
	#validates :username, format: { with: /regex/ } #Validacion con expresión regular
	before_save :set_visits_count #tambien existen otros metodos como "before_save", "before_validation", "after_create", "afeter_save", "after_save :privada, on: :create" entre otros

	def update_visits_count
		#self.save if self.contador_visitas.nil?  #Una vez ya teniendo todos los registros con valor diferente de nil en la base de datos, ahora si podemos borrar esta linea
		self.update(contador_visitas: (self.contador_visitas || 0) + 1) #Le decimos que actualice el contador de visitas con el valor del contador de visitas mas uno
	end

	private

	def set_visits_count
		self.contador_visitas ||= 0 #Inicia el campo contador_visitas en 0 en dado caso de que no traiga nada
	end
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :articulo
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articulos
  has_many :comentarios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
	#before_action :validate_user, except: [:show, :index] #Es como un callback que se ejecuta antes de las funciones, exepto de :index y :show
	#before_action :authenticate_usuario! #Es un metodo de devise que ya viene inyectado en todos los controladores 
	#before_action :authenticate_usuario!, only: [:create, :new] #Y se le puede pasar un hash de opciones para decirle en donde queremos que aplique la validacion de login
	before_action :authenticate_usuario!, except: [:show, :index] #Tambien podemos decirle en donde no queremos que aplique la validacion
	before_action :set_article, except: [:index, :new, :create] #Con esto inicializamos la función con la obtención del articulo desde el params[:id] y nos permite reducir código

	#GET /articulos
	def index
		@articulos = Articulo.all
	end

	#GET /articulos/:id
	def show
		@articulo.update_visits_count
		@comentario = Comentario.new
		#Where
		#Articulo.where(" id = ? ", params[:id]) #Debe traernos el mismo resultado que la consulta de arriba
		#Articulo.where(" cuerpo LIKE ? ", "%hola%") #Debe traernos todos los registros que contengan "hola" en el cuerpo
		#Articulo.where("id = ? AND titulo = ?", params[:id], params[:titulo]) #Debe traernos los articulos donde coincidan el campo id y titulo
		#Articulo.where("id = #{params[:id]}") #Podriamos interpolar la cadena que viene en el parametro directamente pero nos hace suceptibles a SQLInjection
		#Articulo.where.not(" id = 1 ") #Nos debe traer todos los articulos que tengan id diferente de 1
	end

	def edit
	end

	#GET /articulos/new
	def new
		@articulo = Articulo.new #Crea una instancia del modelo Articulo
	end

	#POST /articulos
	def create
		@articulo = current_usuario.articulos.new(articulo_params) #Se lo pasamos directamente porque el hash tiene la misma estructura { titulo: "Titulo", cuerpo: "Cuerpo"}
		
		#Tambien podriamos usar el metodo @articulo.valid? o @articulo.invalid?
		#Si no se puede guardar el articulo, se vuelve a mostrar la vista new
		if @articulo.save
			redirect_to @articulo #Nos redirige
		else
			render :new #No nos mueve de acción, simplemente le dice que use la vista :new
		end
	end

	#DELETE /articulos/:id
	def destroy
		@articulo.destroy #Destroy elimina el articulo de la Base de Datos
		redirect_to articulos_path
	end

	#PUT /articulos/:id
	def update
		if @articulo.update(articulo_params)
			redirect_to @articulo
		else
			render :edit
		end
	end

	private

	def set_article
		@articulo = Articulo.find(params[:id]) #Obtiene el parametro id que viene en la url
	end

	def validate_user
		redirect_to new_usuario_session_path, notice: "Necesitas iniciar sesión"
	end

	def articulo_params
		#{
		#	articulo: {
		#		titulo: ,
		#		cuerpo: 
		#	}
		#}
		params.require(:articulo).permit(:titulo, :cuerpo)
	end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_articulo
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = current_usuario.comentarios.new(comentario_params)
    @comentario.articulo = @articulo #Con esto le decimos que el articulo es el de la URL

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario.articulo, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario.articulo }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario.articulo, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to @articulo, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_articulo
      @articulo = Articulo.find(params[:articulo_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:usuario_id, :articulo_id, :cuerpo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def ejemplos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articulos/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> artículo</h1>
<%= form_for(@articulo) do |f| %>
	<% @articulo.errors.full_messages.each do |mensaje| %>
		<div class="be-red white">
			*<%= mensaje %>
		</div>
	<%end%>
	<div class="field">
		<%= f.text_field :titulo, placeholder: "Título", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.text_area :cuerpo, placeholder: "Escribe aquí el artículo", style: "height:250px", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.submit "Guardar", class:"btn" %>
	</div>
<%end%>

app/views/articulos/edit.html.erb
<div style="width:80%; margin:0 auto;">
	<%= render "form", name: "Editar" %>
</div>

app/views/articulos/index.html.erb
<% @articulos.each do |articulo| %>

<h1><%= link_to articulo.titulo, articulo %></h1>
<div>
	<%= articulo.cuerpo %> - <%= link_to "Eliminar", articulo, method: :delete, class:"red" %>
</div>

<%end%>

<%= link_to "Agregar", new_articulo_path %>

app/views/articulos/new.html.erb
<div style="width:80%; margin:0 auto;">
	<%= render "form" %>
</div>

app/views/articulos/show.html.erb
<h1><%= @articulo.titulo %></h1>
<% unless @articulo.usuario.nil? %>
<p>Escrito por: <%= @articulo.usuario.email %></p>
<%end%>
<p>Visitas: <%= @articulo.contador_visitas %></p>
<div>
	<%= @articulo.cuerpo %>
</div>
<div class="field">
	<h3>Comentarios</h3>
	<%= render "comentarios/form" %>
	<ul id="comments-box">
		<% @articulo.comentarios.each do |comentario| %>
			<li>
				<%= comentario.cuerpo %> - <%= comentario.usuario.email %>
			</li>
		<%end%>
	</ul>
</div>
<div>
	<%= link_to "Editar", edit_articulo_path(@articulo) %>
</div>

app/views/comentarios/_form.html.erb
<%= form_for([@articulo, @comentario], remote: true, html: {id: "comments-form", "data-type":"json" }) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Articulo</th>
      <th>Cuerpo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.usuario %></td>
        <td><%= comentario.articulo %></td>
        <td><%= comentario.cuerpo %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @comentario.usuario %>
</p>

<p>
  <strong>Articulo:</strong>
  <%= @comentario.articulo %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @comentario.cuerpo %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<%= render "partials/navigation" %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/partials/_navigation.html.erb
<header>
	<nav class="be-red white large-padding">
		<ul class="no-list row center-xs middle-xs">
			<li class="col-md">
				<h1 class="no-margin">Blog Noel</h1>
			</li>
			<li class="col-md">
				<%= link_to "Inicio", root_path %>
			</li>
			<li class="col-md">
				<%= link_to "Diseño", root_path %>
			</li>
			<li class="col-md">Programacion</li>
			<li class="col-md">Tecnologia</li>
			<% if usuario_signed_in? %>
				<li class="col-md">
					<%= link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete %>
				</li>
			<%else%>
				<li class="col-md">
					<%= link_to "Iniciar sesión", new_usuario_session_path %>
				</li>
				<li class="col-md">
					<%= link_to "Crear cuenta", new_usuario_registration_path %>
				</li>
			<%end%>
		</ul>
	</nav>
</header>

app/views/welcome/ejemplos.html.erb
<h1>Hola de nuevo</h1>
<p>Renombrado el equivocado</p>

<h2>Iterando un faken arreglo</h2>
<% [1,2,3,4].each do |number| %>
<p>Numero: <%= number * 2 %></p>
<% end %>
<%= [1,2,3,4] %>

<h2>Imprimiendo una variable</h2>
<% nombre = "noel" %>
<%= "Hola #{nombre}" %>

app/views/welcome/index.html.erb
<%if usuario_signed_in? %>
<h1>Bienvenido <%= current_usuario.email %></h1>
<%end%>
<%= link_to "Mis ejemplos", welcome_ejemplos_path %>